server:
  port: 8081
  servlet:
    context-path: /shop

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

onboarding.uri: https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi

payment-api:
  apiKey: '012345678901'
  apiLogin: '012345678901'
  order:
    accountId: 1
    notifyUrl: http://prueba-pago.com.co
  amount:
    minimum: 11000
    maximum: 18308500

credit:
  card:
    visa: "^(4)(\\d{12}|\\d{15})$|^(606374\\d{10}$)"
    diners: "(^[35](?:0[0-5]|[68][0-9])[0-9]{11}$)|(^30[0-5]{11}$)|(^3095(\\d{10})$)|(^36{12}$)|(^3[89](\\d{12})$)"
    discover: "^(6011\\d{12})$|^(64[4-9]\\{13})$|^(65\\d{14})$"
    amex: "^(3[47]\\d{13})$"
    mastercard: "^(5[1-5]\\d{14}$)|^(2(?:2(?:2[1-9]|[3-9]||d)|[3-6]\\d\\d|7(?:[01]\\d|20))\\d{12}$)"
    naranja: "^(589562)\\d{10}$"
    codensa: "^590712(\\d{10})$"

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectionTimeout: 30000
        readTimeout: 30000
      "[payment]":
        connectionTimeout: 30000
        readTimeout: 30000