server:
  port: 8081
  servlet:
    context-path: /shop

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: onboarding.log
  level:
    org.springframework: info
    org.hibernate: debug

onboarding.uri: https://sandbox.api.payulatam.com/payments-api/4.0/service.cgi

payment-api:
  apiKey: 4Vj8eK4rloUd272L48hsrarnUA
  apiLogin: pRRXKOl8ikMmt9u

feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectionTimeout: 5000
        readTimeout: 5000
      "[payment]":
        connectionTimeout: 5000
        readTimeout: 5000